SERIAL_DRIVER = vendor
# SERIAL_DRIVER = bitbang
ENCODER_ENABLE = yes
SPLIT_KEYBOARD = yes
BOARD = GENERIC_RP_RP2040
TRI_LAYER_ENABLE = yes
LTO_ENABLE = yes
CONSOLE_ENABLE = yes
# MATRIX_ENABLE = no

# SRC += matrix.c
